/**
 * List of icon files.
 * This file is autogenerated. Do not edit directly.
 */

const list = [
  'lg32/standardAccount.svg',
  'rg24/systemActionABCKeypad.svg',
  'sm16/systemAdd.svg',
];

export default list;
